# --- IA2C NS specific parameters ---

action_selector: "soft_policies_msg"
mask_before_softmax: True

runner: "parallel_msg_fusion"

buffer_size: 10
batch_size_run: 10
batch_size: 10

env_args:
  state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval_or_tau: 0.01

lr: 0.0005

obs_agent_id: False
obs_last_action: False
obs_individual_obs: False

obs_msg: True
use_state_diff: True
msg_loss_coef: 1.0
msg_fusion: true
msg_ext_len: 5
msg_sd_len: 5

mac: "non_shared_msg_fusion_mac"
agent: "rnn_ns_msg"
agent_output_type: "pi_logits"
learner: "actor_critic_msg_fusion_learner"
entropy_coef: 0.05
standardise_rewards: True
use_rnn: True
q_nstep: 5 # 1 corresponds to normal r + gammaV
critic_type: "ac_critic_ns_msg"
name: "ia2c_ns_msg_fusion"

t_max: 20050000