# --- IA2C NS specific parameters ---

action_selector: "soft_policies_msg"
mask_before_softmax: True

runner: "parallel_msg"

buffer_size: 10
batch_size_run: 10
batch_size: 10

env_args:
  state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval_or_tau: 0.01

lr: 0.0005

obs_agent_id: False
obs_last_action: False
obs_individual_obs: False

obs_msg: True
msg_len: 10
msg_loss_coef: 1.0
extr_rwd_coef: 0.1

mac: "non_shared_msg_mac"
agent: "rnn_ns_msg"
agent_output_type: "pi_logits"
learner: "actor_critic_msg_conf_ext_learner"
entropy_coef: 0.01
standardise_rewards: True
use_rnn: True
q_nstep: 5 # 1 corresponds to normal r + gammaV
critic_type: "ac_critic_ns_msg"
name: "ia2c_ns_msg_conf_ext"

t_max: 20050000