env: "emc_didactic"

env_args:
  key: "emc_didactic_placeholder_key"
  pretrained_wrapper: null
  inner_args:
    n_agents: 2
    # map_dims: [12, 5]
    delay: 2
    coop_reward: 10.0
    incoop_penalty: 1.0
    time_penalty: 0.02
    max_steps: 200

test_greedy: True
test_nepisode: 100
test_interval: 50000
log_interval: 50000
replay_interval: null   # 100000   # currently, this overrides the save_replay in default.yaml
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 20500000
