env: "gymma_indep_rwd"

env_args:
  key: null
  time_limit: 100
  pretrained_wrapper: null
  # inner_args:
  #   reward_share_wgt: 0.25
  #   shelf_timeout_penalty: 100.0

test_greedy: True
test_nepisode: 100
test_interval: 50000
log_interval: 50000
replay_interval: 1000000   # 100000   # currently, this overrides the save_replay in default.yaml
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 20500000
